### PR TITLE
Update PlaceNL.py

### PR DESCRIPTION
**Pull request by cChimney**
Easier for multiple accounts, save accounts in accounts.txt

### CODE REVIEW

**Comment by JasperRab** [comment]
Can't you make that into a alternative argument? That would mean that current scripts/bots won't need a lot of work updating.

**Comment by cChimney** [comment]
Yes that is a good alternative ofcourse, like --config accounts.txt ?

**Comment by JasperRab** [comment]
Yea for example, just so it doesn't break -u/--user.

**Comment by lrvdijk** [comment]
I'm working on a config file implementation 👍

**Pull request closed without merging**
